input {
  beats {
    port => 5044
  }
}

filter {
  if [type] == "audit" {
    mutate {
      add_field => { "[@metadata][target_index]" => "audit_logs_dev" }
    }
    
    # Anonimização de dados sensíveis
    if [user_wallet] {
      ruby {
        code => "event.set('user_wallet', Digest::SHA256.hexdigest(event.get('user_wallet')))"
      }
    }
    
    if [ip_address] {
      ruby {
        code => "event.set('ip_address', event.get('ip_address').split('.').map { |x| x.to_i < 255 ? 'x' : x }.join('.'))"
      }
    }
  }
}

output {
  if [@metadata][target_index] {
    elasticsearch {
      hosts => ["${ELASTICSEARCH_URL}"]
      index => "%{[@metadata][target_index]}-%{+YYYY.MM.dd}"
      user => "${ELASTICSEARCH_USER}"
      password => "${ELASTICSEARCH_PASSWORD}"
    }
  } else {
    elasticsearch {
      hosts => ["${ELASTICSEARCH_URL}"]
      index => "ibeleve-logs-%{+YYYY.MM.dd}"
      user => "${ELASTICSEARCH_USER}"
      password => "${ELASTICSEARCH_PASSWORD}"
    }
  }
} 