apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  infura-key: <base64-encoded-infura-key>
  alchemy-key: <base64-encoded-alchemy-key>
  jwt-secret: <base64-encoded-jwt-secret>
  ollama-api-key: <base64-encoded-ollama-api-key> 