import { Registry, Counter, Histogram, Gauge } from 'prom-client';
declare const register: Registry;
export declare const httpRequestsTotal: Counter<"method" | "path" | "status">;
export declare const httpRequestDuration: Histogram<"method" | "path" | "status">;
export declare const httpRequestErrors: Counter<"method" | "path" | "error_type">;
export declare const zkpProofGeneration: Counter<"status" | "type">;
export declare const zkpProofVerification: Counter<"status" | "type">;
export declare const zkpProofGenerationDuration: Histogram<"type">;
export declare const openFinanceRequests: Counter<"status" | "endpoint">;
export declare const openFinanceErrors: Counter<"error_type" | "endpoint">;
export declare const openFinanceTokenExpirations: Counter<string>;
export declare const cacheHits: Counter<"cache_type">;
export declare const cacheMisses: Counter<"cache_type">;
export declare const cacheSize: Gauge<"cache_type">;
export declare const activeUsers: Gauge<string>;
export declare const activeSessions: Gauge<string>;
export declare const auditLogsTotal: Counter<"status" | "event_type">;
export declare const auditLogErrors: Counter<"error_type">;
export declare const metrics: {
    httpRequestsTotal: Counter<"method" | "path" | "status">;
    httpRequestDuration: Histogram<"method" | "path" | "status">;
    httpRequestErrors: Counter<"method" | "path" | "error_type">;
    zkpProofGeneration: Counter<"status" | "type">;
    zkpProofVerification: Counter<"status" | "type">;
    zkpProofGenerationDuration: Histogram<"type">;
    openFinanceRequests: Counter<"status" | "endpoint">;
    openFinanceErrors: Counter<"error_type" | "endpoint">;
    openFinanceTokenExpirations: Counter<string>;
    cacheHits: Counter<"cache_type">;
    cacheMisses: Counter<"cache_type">;
    cacheSize: Gauge<"cache_type">;
    activeUsers: Gauge<string>;
    activeSessions: Gauge<string>;
    auditLogsTotal: Counter<"status" | "event_type">;
    auditLogErrors: Counter<"error_type">;
};
export { register };
