groups:
  - name: high-priority
    rules:
      - alert: ServicoIndisponivel
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Serviço indisponível: {{ $labels.instance }}"
          description: "O serviço {{ $labels.job }} está indisponível há mais de 1 minuto."

      - alert: TaxaDeErrosAlta
        expr: sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Taxa de erros alta"
          description: "A taxa de erros está acima de 5% nos últimos 5 minutos."

      - alert: LatenciaAlta
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 2
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Latência alta"
          description: "95% das requisições estão demorando mais de 2 segundos."

      - alert: UsoDeMemoriaAlto
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Uso de memória alto"
          description: "O uso de memória está acima de 90% há mais de 5 minutos."

      - alert: UsoDeCPUAlto
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Uso de CPU alto"
          description: "O uso de CPU está acima de 90% há mais de 5 minutos."

      - alert: EspacoEmDiscoAlto
        expr: (node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}) / node_filesystem_size_bytes{mountpoint="/"} * 100 > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Espaço em disco alto"
          description: "O uso de disco está acima de 90% há mais de 5 minutos." 