# Configurações básicas
port 6379
bind 0.0.0.0
protected-mode yes

# Autenticação
requirepass ibeleve123

# Persistência
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec

# Configurações de memória
maxmemory 512mb
maxmemory-policy allkeys-lru

# Configurações de log
loglevel notice
logfile ""

# Configurações de segurança
rename-command FLUSHDB ""
rename-command FLUSHALL ""
rename-command DEBUG "" 